"use strict";

//Strings used to retrieve objects from the view / storing classes from css file
const ACTIVECATEGORYCLASS = "category-button-active",
    ACTIVECATEGORYFIELD = "selectedCategory",
    BADINPUTS = "Ungültige Eingabe",
    SUCCESS = "success",
    CATEGORIES = "SavedCategories",
    CATEGORYBUTTONCLASS = "category-button",
    CATEGORYLIST = "categoryList",
    CATEGORYNAMELABELCLASS = "category-name-label",
    CATEGORYTASKAMOUNTLABELCLASS = "category-task-amount-label",
    FINISHEDTASKLIST = "finishedTaskList",
    HIGHLIGHTED = "highlighted",
    LOADAMOUNT = "loadMoreAmount",
    NEWCATEGORYINPUT = "newCategoryInput",
    NEWTASKINPUT = "newTaskInput",
    SEARCHTEXT = "searchText",
    SHOWFINISHEDTASKS = "showFinishedTasks",
    TASKPOPUP = "TaskPopup",
    TASKPOPUPDEADLINE = "taskPopupDeadline",
    TASKPOPUPDESCRIPTION = "taskPopupDescription",
    TASKPOPUPNAME = "taskPopupName",
    TASKS = "SavedTasks",
    UNFINISHEDTASKLIST = "unfinishedTaskList",
    GET = "GET",
    POST = "POST";
